import type { NextPage } from "next";
import Head from "next/head";
import { Box } from "@obolnetwork/obol-ui";
import { Navbar } from "../components/molecules/Navbar/Navbar";
import { HeroSection } from "../components/organisms/HeroSection/HeroSection";

const Home: NextPage = () => {
  return (
    <Box css={{ padding: "0 2rem" }}>
      <Head>
        <title>Obol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box css={{ pt: "$xl", px: "calc($2xl * 2)" }}>
        <Navbar />
      </Box>
      <Box
        as="main"
        css={{
          minHeight: "100vh",
          padding: "calc($1xl * 5) calc($2xl * 2)",
          flex: 1,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        <HeroSection />
      </Box>
    </Box>
  );
};

export default Home;
