import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Box, Button } from "@obolnetwork/obol-ui";
import { Navbar } from "../components/molecules/Navbar/Navbar";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box css={{ mt: "32px", mx: "96px" }}>
        <Navbar />
      </Box>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Obol Site</a>
        </h1>
        <div style={{ display: "flex", gap: 10 }}>
          <Button>Read the docs</Button>
          <Button color="primary">Read the docs</Button>
          <Button color="secondary">Edit</Button>
          <Button variant="nav">Join to Community</Button>
        </div>
      </main>
    </div>
  );
};

export default Home;
